version: "3"
services:
  test-container:
    image: test-interface
    container_name: test-runner
    command: ["npm", "run", "test:ci"]
    depends_on: ["firefox", "chrome", "test-server", "test-interface"]
  test-interface:
    image: test-interface
    container_name: test-interface
  test-server:
    image: docker.pkg.github.com/b-m-f/wirt/WirtBot:release
    container_name: test-server
    environment:
      "PUBLIC_KEY": "1lLU3VhXsrSGMxESmqfY4m2oEVkpfEHyKlCQU6MMPsI="
      "ALLOWED_ORIGIN": "http://localhost:8080"
      "RUST_LOG": "debug"
      "MANAGED_DNS_ENABLED": 1
  chrome:
    image: selenium/standalone-chrome
    container_name: chrome
  firefox:
    image: selenium/standalone-firefox
    container_name: firefox
