version: "3"
services:
  test-container:
    image: test-interface
    container_name: test-runner
    command: ["sh", "/app/wait-for.sh", "firefox:4444", "--", "npm", "run", "test:e2e:headless:watch"]
    depends_on: ["firefox", "chrome", "test-server", "test-interface"]
    volumes:
      - ./download_folder:/Downloads/
      - ../../tests:/app/tests
  test-interface:
    image: test-interface
    container_name: test-interface
  test-server:
    image: bmff/wirtbot:release
    container_name: test-server
    environment:
      "PUBLIC_KEY": "1lLU3VhXsrSGMxESmqfY4m2oEVkpfEHyKlCQU6MMPsI="
      "ALLOWED_ORIGIN": "http://localhost:8080"
      "RUST_LOG": "debug"
      "MANAGED_DNS_ENABLED": 1
  chrome:
    image: selenium/standalone-chrome:latest
    container_name: chrome
  firefox:
    image: selenium/standalone-firefox:latest
    container_name: firefox
    volumes:
      - ./download_folder:/root/Downloads/
