- name: Install vim
  apt:
    name:
      - vim
      - docker.io
      - docker-compose
    state: present


- name: Copy docker-daemon config to machine
  template:
    src: "templates/docker-daemon.json.j2"
    dest: "/etc/docker/daemon.json"
    mode: 0640

- name: Restart docker to load daemon config
  systemd:
    state: restarted
    name: docker

- name: Check for docker network
  shell: docker network list | grep dockernet
  register: network_exists
  ignore_errors: yes

- name: Create docker network to have control over it with firewall
  command: docker network create --subnet=172.10.17.0/24 dockernet
  when: network_exists is failed
