version: "3"
services:
  test-container:
    image: test-interface
    container_name: test-container
    command: ["npm", "run", "test:ci"]
    depends_on: ["firefox", "chrome", "test-server"]
  test-server:
    image: test-server
    container_name: test-server
  chrome:
    image: selenium/standalone-chrome
    container_name: chrome
  firefox:
    image: selenium/standalone-firefox
    container_name: firefox
