- name: Update and upgrade apt packages
  apt:
    upgrade: "yes"
    update_cache: "yes"

- name: Enable unattended upgrades for security packages
  apt:
    name:
     - unattended-upgrades
     - apt-listchanges
    state: present

