- name: Install fail2ban
  apt:
    name: fail2ban
    state: present

- name: override the basic fail2ban configuration with .local file
  template:
    src: templates/fail2ban.jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644

- name: enable fail2ban
  service:
    name: fail2ban
    state: started
    enabled: true
