- name: install NFT
  apt:
    name:
      - nftables
    state: present

- name: set a strict default nftables configuration
  template:
    src: templates/nftables.conf.j2
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: 0640

- name: Start and enable nftables
  systemd:
    state: started
    name: nftables
    enabled: yes
