- name: Create directories for WirtBot-Interface
  file:
    path: "/home/{{ maintainer_username }}/WirtBot-Interface"
    owner: "{{ maintainer_username }}"
    group: "{{ maintainer_username }}"
    state: directory
    mode: '0750'

- name: Copy docker-compose file to machine
  template:
    src: "templates/WirtBot-Interface.docker-compose.yml.j2"
    dest: "/home/{{ maintainer_username }}/WirtBot-Interface/docker-compose.yml"
    owner: "{{ maintainer_username }}"
    group: "{{ maintainer_username }}"
    mode: 0640

- name: Start WirtBot docker service
  docker_compose:
    project_src: "/home/{{ maintainer_username }}/WirtBot-Interface"
    build: yes
    recreate: always
    pull: yes